---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - slurm::nfs
      - slurm::controller
      - slurm::compute
    attributes:
